/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaquotes;

import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
            Gson gson = new Gson();
            String path = "/Users/dhackle/codefellows/401/labs/lab8/javaquotes/src/main/resources/recentquotes.json";
            QuoteReader read = new QuoteReader(path);
            read.readFromFile();

            Quote[] quotes = gson.fromJson(read.getReader(), Quote[].class);
            Quotes qArray = new Quotes(quotes);

            System.out.println(qArray.grabOneQuote());
    }
}
